# HRS Style Guide: Jekyll Config
#
# Note, this file is *not* reloaded automatically when you use
# `bundle exec jekyll serve`. If you change this file, please restart the
# server process.

# Site settings.
title: HRS Style Guide
email: adam.turner@wsu.edu
description: A style guide for the WSU HRS website.
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: admturner
github_repository_url:
version: 0.8.2

# Exclude from processing.
exclude:
  - Gemfile*
  - node_modules
  - vendor
  - README.md
  - CHANGELOG.md
  - LICENSE.txt

# Build settings.
markdown: kramdown
permalink: /blog/:year/:month/:day/:title.html
show_dir_listing: false
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  patterns:
    title: Pattern Library
    output: true
    permalink: /patterns/:path/
  usage:
    title: Usage
    output: false
  styleguide:
    title: Style Guide
    output: true
    permalink: /styleguide/:path/

defaults:
  -
    scope:
      path: ""
      type: "patterns"
    values:
      layout: pattern
  -
    scope:
      path: ""
      type: "usage"
    values:
      layout: usage
  -
    scope:
      path: ""
      type: "styleguide"
    values:
      layout: page
  -
    scope:
      path: "assets/images"
    values:
      image: true
