# Empty Style Guide: Jekyll Config
#
# Note, this file is *not* reloaded automatically when you use
# `bundle exec jekyll serve`. If you change this file, please restart the
# server process.

# Site settings.
title: Empty Style Guide
email: support@adamturner.org
description: A style guide framework.
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: admturner
github_repository_url: https://github.com/admturner/empty-style-guide
markdown: kramdown
version: 0.2.0

# Exclude from processing.
exclude:
  - Gemfile*
  - node_modules
  - vendor
  - README.md
  - CHANGELOG.md
  - LICENSE.txt

# Build settings.
permalink: /blog/:year/:month/:day/:title.html
plugins:
  - jekyll-feed
  - jekyll-seo-tag
